project:
  type: website
  output-dir: docs

website:
  title: "Leila Dagan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: More about Me 
      - href: restoration_rest.qmd
        text: Restoration and Rest areas at UCSB
      - href: free_page.qmd
        text: BIOMA Fieldwork
      - href: resume.qmd
        text: resume 

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    mainfont: IBM Plex Serif
    page-layout: full

editor: visual

