project:
  type: website
  output-dir: docs

website:
  title: "Leila Dagan Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project_page.qmd
      - free_page.qmd
      - resume.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

